"""initial_schema

Revision ID: fa7f6c531edd
Revises: 
Create Date: 2026-06-22 15:45:04.947998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7f6c531edd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_number', name='uq_routes_route_number')
    )
    op.create_index('ix_routes_is_active', 'routes', ['is_active'], unique=False)
    op.create_index('ix_routes_source_destination', 'routes', ['source', 'destination'], unique=False)
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=40), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('bus_type', sa.String(length=50), nullable=False),
    sa.Column('operator_name', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity IS NULL OR capacity > 0', name='ck_buses_capacity_positive'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number', name='uq_buses_registration_number')
    )
    op.create_index('ix_buses_bus_type', 'buses', ['bus_type'], unique=False)
    op.create_index('ix_buses_is_active', 'buses', ['is_active'], unique=False)
    op.create_index('ix_buses_route_status', 'buses', ['route_id', 'status'], unique=False)
    op.create_table('bus_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed_kmph', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading_degrees', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('heading_degrees IS NULL OR (heading_degrees >= 0 AND heading_degrees <= 359)', name='ck_bus_locations_heading_range'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_bus_locations_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_bus_locations_longitude_range'),
    sa.CheckConstraint('speed_kmph IS NULL OR speed_kmph >= 0', name='ck_bus_locations_speed_non_negative'),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bus_locations_bus_recorded_at', 'bus_locations', ['bus_id', 'recorded_at'], unique=False)
    op.create_index('ix_bus_locations_recorded_at', 'bus_locations', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bus_locations_recorded_at', table_name='bus_locations')
    op.drop_index('ix_bus_locations_bus_recorded_at', table_name='bus_locations')
    op.drop_table('bus_locations')
    op.drop_index('ix_buses_route_status', table_name='buses')
    op.drop_index('ix_buses_is_active', table_name='buses')
    op.drop_index('ix_buses_bus_type', table_name='buses')
    op.drop_table('buses')
    op.drop_index('ix_routes_source_destination', table_name='routes')
    op.drop_index('ix_routes_is_active', table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
